apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  restartPolicy: Never 
  containers:
  - name: nginx-helloworld
    image: nginx:latest
    command: ["/bin/sh", "-c"]
    args: 
      - echo "hello-world";
        sleep 900;
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
    